"""add disciplina to professor

Revision ID: ed90e966c7ce
Revises: 5e4dcdece1f4
Create Date: 2025-11-16 20:12:01.519748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed90e966c7ce'
down_revision = '5e4dcdece1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disciplina', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_column('disciplina')

    # ### end Alembic commands ###
